package fr.solutec;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import fr.solutec.entities.Contrainte;
import fr.solutec.entities.Evenement;
import fr.solutec.entities.Utilisateur;
import fr.solutec.entities.Ingredient;
import fr.solutec.entities.Recette;
import fr.solutec.entities.ListeCourse;
import fr.solutec.entities.Participe;
import fr.solutec.entities.IngredientCourse;
import fr.solutec.entities.IngredientRecette;
import fr.solutec.entities.Ami;
import fr.solutec.entities.Avis;
import fr.solutec.repository.AmiRepository;
import fr.solutec.repository.AvisRepository;
import fr.solutec.repository.ContrainteRepository;
import fr.solutec.repository.IngredientCourseRepository;
import fr.solutec.repository.IngredientRecetteRepository;
import fr.solutec.repository.IngredientRepository;
import fr.solutec.repository.ListeCourseRepository;
import fr.solutec.repository.ParticipeRepository;
import fr.solutec.repository.RecetteRepository;
import fr.solutec.repository.UtilisateurRepository;
import fr.solutec.repository.EvenementRepository;

@SpringBootApplication
public class FrigidoomApplication implements CommandLineRunner {
	
	@Autowired 
	private UtilisateurRepository utilisateurRepos ;
	
	@Autowired 
	private ContrainteRepository contrainteRepos ;
	
	@Autowired 
	private IngredientRepository ingredientRepos ;
	
	@Autowired 
	private RecetteRepository recetteRepos ;
	
	@Autowired 
	private IngredientRecetteRepository ingredientRecetteRepos ;
	
	@Autowired 
	private ListeCourseRepository listeCourseRepos ;
	
	@Autowired 
	private IngredientCourseRepository ingredientCourseRepos ;
	
	@Autowired
	private AmiRepository amiRepos;
	
	@Autowired
	private AvisRepository avisRepos;
	
	@Autowired
	private EvenementRepository eventRepos;
	
	@Autowired
	private ParticipeRepository participeRepos;
	
//Cette commande s'exécute avant le main
	public void run(String... args) throws Exception {
		
		//Insérer des ingrédients
		Ingredient i1 = new Ingredient(null,"Cuisse de poulet", "Viande");
		Ingredient i2 = new Ingredient(null,"Ail", "Légume");
		Ingredient i3 = new Ingredient(null,"Basilic", "Herbe aromatique");
		Ingredient i4 = new Ingredient(null,"Beurre", "Produit laitier");
		Ingredient i5 = new Ingredient(null,"Blanc de poulet", "Viande");
		Ingredient i6 = new Ingredient(null,"Blanquette de veau", "Viande");
		Ingredient i7 = new Ingredient(null,"Boeuf", "Viande");
		Ingredient i8 = new Ingredient(null,"Boeuf haché", "Viande");
		Ingredient i9 = new Ingredient(null,"Bouillon de légumes", "Condiment");
		Ingredient i10 = new Ingredient(null,"Bouillon de poule", "Condiment");
		Ingredient i11 = new Ingredient(null,"Bouillon de volaille dilué", "Condiment");
		Ingredient i12 = new Ingredient(null,"Bouquet garni", "Herbe aromatique");
		Ingredient i13 = new Ingredient(null,"Boeuf bourguignon", "Viande");
		Ingredient i14 = new Ingredient(null,"Carotte", "Légume");
		Ingredient i15 = new Ingredient(null,"Céleri", "Légume");
		Ingredient i16 = new Ingredient(null,"Champignons", "Légume");
		Ingredient i17 = new Ingredient(null,"Chili en poudre", "Epice");
		Ingredient i18 = new Ingredient(null,"Ciboulette", "Herbe aromatique");
		Ingredient i19 = new Ingredient(null,"Citron", "Fruit");
		Ingredient i20 = new Ingredient(null,"Citron vert", "Fruit");
		Ingredient i21 = new Ingredient(null,"Citronnelle", "Herbe aromatique");
		Ingredient i22 = new Ingredient(null,"Concentrés de tomates", "Légume");
		Ingredient i23 = new Ingredient(null,"Coriandre", "Herbe aromatique");
		Ingredient i24 = new Ingredient(null,"Courgettes", "Légume");
		Ingredient i25 = new Ingredient(null,"Crême fraîche", "Produit laitier");
		Ingredient i26 = new Ingredient(null,"Crevette", "Produit de la mer");
		Ingredient i27 = new Ingredient(null,"Cube de bouillon", "Condiment");
		Ingredient i28 = new Ingredient(null,"Cumin arabe", "Epices");
		Ingredient i29 = new Ingredient(null,"Cumin en poudre", "Epices");
		Ingredient i30 = new Ingredient(null,"Curry", "Epices");
		Ingredient i31 = new Ingredient(null,"Eau", "Boisson");
		Ingredient i32 = new Ingredient(null,"Echalottes", "Légume");
		Ingredient i33 = new Ingredient(null,"Epices", "Epice");
		Ingredient i34 = new Ingredient(null,"Epices à couscous", "Epice");
		Ingredient i35 = new Ingredient(null,"Escalope de dinde", "Epice");
		Ingredient i36 = new Ingredient(null,"Farine", "Farine");
		Ingredient i37 = new Ingredient(null,"Feuille de laurier", "Herbe aromatique");
		Ingredient i38 = new Ingredient(null,"Filet de poulet", "Viande");
		Ingredient i39 = new Ingredient(null,"Fromage râpé", "Produit laitier");
		Ingredient i40 = new Ingredient(null,"Gingembre", "Epice");
		Ingredient i41 = new Ingredient(null,"Graine de coriandre", "Epice");
		Ingredient i42 = new Ingredient(null,"Haricots rouges", "Légume");
		Ingredient i43 = new Ingredient(null,"Harissa", "Epice");
		Ingredient i44 = new Ingredient(null,"Huile", "Huile");
		Ingredient i45 = new Ingredient(null,"Huile d'olive", "Huile");
		Ingredient i46 = new Ingredient(null,"Huile de sésame", "Huile");
		Ingredient i47 = new Ingredient(null,"Jaune d'oeuf", "Oeuf");
		Ingredient i48 = new Ingredient(null,"Citron", "Fruit");
		Ingredient i49 = new Ingredient(null,"Lait", "Produit laitier");
		Ingredient i50 = new Ingredient(null,"Lait de coco", "Légume");
		Ingredient i51 = new Ingredient(null,"Lardons fumés", "Viande");
		Ingredient i52 = new Ingredient(null,"Lasagnes", "Pâtes");
		Ingredient i53 = new Ingredient(null,"Macis", "Epice");
		Ingredient i54 = new Ingredient(null,"Merguez", "Viande");
		Ingredient i55 = new Ingredient(null,"Miel", "Miel");
		Ingredient i56 = new Ingredient(null,"Moutarde", "Condiment");
		Ingredient i57 = new Ingredient(null,"Moutarde de dijon", "Condiment");
		Ingredient i58 = new Ingredient(null,"Muscade", "Epice");
		Ingredient i59 = new Ingredient(null,"Navets", "Légume");
		Ingredient i60 = new Ingredient(null,"Oeufs", "Oeuf");
		Ingredient i61 = new Ingredient(null,"Oignon", "Legume");
		Ingredient i62 = new Ingredient(null,"Orange", "Fruit");
		Ingredient i63 = new Ingredient(null,"Parmesan", "Produit laitier");
		Ingredient i64 = new Ingredient(null,"Pâte de curry", "Epice");
		Ingredient i65 = new Ingredient(null,"Pâtes", "Pâtes");
		Ingredient i66 = new Ingredient(null,"Pilons de poulet", "Viande");
		Ingredient i67 = new Ingredient(null,"Piment de Cayenne", "Epice");
		Ingredient i68 = new Ingredient(null,"Poireau", "Légume");
		Ingredient i69 = new Ingredient(null,"Pois chiches", "Légume");
		Ingredient i70 = new Ingredient(null,"Pois gourmands", "Légume");
		Ingredient i71 = new Ingredient(null,"Poivron", "Légume");
		Ingredient i72 = new Ingredient(null,"Poivron rouge", "Légume");
		Ingredient i73 = new Ingredient(null,"Poivron vert", "Légume");
		Ingredient i74 = new Ingredient(null,"Pomme de terre", "Feculent");
		Ingredient i75 = new Ingredient(null,"Potimarron", "Légume");
		Ingredient i76 = new Ingredient(null,"Poulet fermier", "Viande");
		Ingredient i77 = new Ingredient(null,"Purée de tomates", "Légume");
		Ingredient i78 = new Ingredient(null,"Reblochon", "Produit laitier");
		Ingredient i79 = new Ingredient(null,"Riz basmati", "Feculent");
		Ingredient i80 = new Ingredient(null,"Rôti de boeuf", "Viande");
		Ingredient i81 = new Ingredient(null,"Sauce soja", "Sauce");
		Ingredient i82 = new Ingredient(null,"Sucre", "Sucre");
		Ingredient i83 = new Ingredient(null,"Thym", "Herbe aromatique");
		Ingredient i84 = new Ingredient(null,"Tomates", "Légume");
		Ingredient i85 = new Ingredient(null,"Tomates cerises", "Légume");
		Ingredient i86 = new Ingredient(null,"Vin blanc", "Boisson");
		Ingredient i87 = new Ingredient(null,"Vin rouge", "Boisson");
		Ingredient i88 = new Ingredient(null,"Vinaigre de cidre", "Vinaigre");
		Ingredient i89 = new Ingredient(null,"Legumes", "Legume");
		Ingredient i90 = new Ingredient(null,"Bouillon de boeuf", "Condiment");
		Ingredient i91 = new Ingredient(null,"Persil", "Herbe aromatique");
		ingredientRepos.save(i1);
		ingredientRepos.save(i2);
		ingredientRepos.save(i3);
		ingredientRepos.save(i4);
		ingredientRepos.save(i5);
		ingredientRepos.save(i6);
		ingredientRepos.save(i7);
		ingredientRepos.save(i8);
		ingredientRepos.save(i9);
		ingredientRepos.save(i10);
		ingredientRepos.save(i11);
		ingredientRepos.save(i12);
		ingredientRepos.save(i13);
		ingredientRepos.save(i14);
		ingredientRepos.save(i15);
		ingredientRepos.save(i16);
		ingredientRepos.save(i17);
		ingredientRepos.save(i18);
		ingredientRepos.save(i19);
		ingredientRepos.save(i20);
		ingredientRepos.save(i21);
		ingredientRepos.save(i22);
		ingredientRepos.save(i23);
		ingredientRepos.save(i24);
		ingredientRepos.save(i25);
		ingredientRepos.save(i26);
		ingredientRepos.save(i27);
		ingredientRepos.save(i28);
		ingredientRepos.save(i29);
		ingredientRepos.save(i30);
		ingredientRepos.save(i31);
		ingredientRepos.save(i32);
		ingredientRepos.save(i33);
		ingredientRepos.save(i34);
		ingredientRepos.save(i35);
		ingredientRepos.save(i36);
		ingredientRepos.save(i37);
		ingredientRepos.save(i38);
		ingredientRepos.save(i39);
		ingredientRepos.save(i40);
		ingredientRepos.save(i41);
		ingredientRepos.save(i42);
		ingredientRepos.save(i43);
		ingredientRepos.save(i44);
		ingredientRepos.save(i45);
		ingredientRepos.save(i46);
		ingredientRepos.save(i47);
		ingredientRepos.save(i48);
		ingredientRepos.save(i49);
		ingredientRepos.save(i50);
		ingredientRepos.save(i51);
		ingredientRepos.save(i52);
		ingredientRepos.save(i53);
		ingredientRepos.save(i54);
		ingredientRepos.save(i55);
		ingredientRepos.save(i56);
		ingredientRepos.save(i57);
		ingredientRepos.save(i58);
		ingredientRepos.save(i59);
		ingredientRepos.save(i60);
		ingredientRepos.save(i61);
		ingredientRepos.save(i62);
		ingredientRepos.save(i63);
		ingredientRepos.save(i64);
		ingredientRepos.save(i65);
		ingredientRepos.save(i66);
		ingredientRepos.save(i67);
		ingredientRepos.save(i68);
		ingredientRepos.save(i69);
		ingredientRepos.save(i70);
		ingredientRepos.save(i71);
		ingredientRepos.save(i72);
		ingredientRepos.save(i73);
		ingredientRepos.save(i74);
		ingredientRepos.save(i75);
		ingredientRepos.save(i76);
		ingredientRepos.save(i77);
		ingredientRepos.save(i78);
		ingredientRepos.save(i79);
		ingredientRepos.save(i80);
		ingredientRepos.save(i81);
		ingredientRepos.save(i82);
		ingredientRepos.save(i83);
		ingredientRepos.save(i84);
		ingredientRepos.save(i85);
		ingredientRepos.save(i86);
		ingredientRepos.save(i87);
		ingredientRepos.save(i88);
		ingredientRepos.save(i89);
		ingredientRepos.save(i90);
		ingredientRepos.save(i91);
		
		//Insérer des contraintes 
		List<String> typesViande = Arrays.asList("Viande");
		List<Ingredient> ingredientsVegetarien = contrainteRepos.getIngredientsByType(typesViande);
		Contrainte c1 = new Contrainte(null, "regime", "vegetarien", ingredientsVegetarien);
		
		List<String> typesViandeOeuf = Arrays.asList("Viande", "Oeuf");
		List<Ingredient> ingredientsVegan = contrainteRepos.getIngredientsByType(typesViandeOeuf);
		Contrainte c2 = new Contrainte(null, "regime", "vegan", ingredientsVegan);

		Contrainte c3 = new Contrainte (null, "regime", "flexitarien", Arrays.asList());
		Contrainte c4 = new Contrainte (null, "allergie", "allergie aux oeufs",Arrays.asList(i60));
		Contrainte c5 = new Contrainte (null, "allergie", "allergie à la coriandre", Arrays.asList(i23));
		Contrainte c6 = new Contrainte (null, "déteste", "la coriandre", Arrays.asList(i23));
		contrainteRepos.save(c1);
		contrainteRepos.save(c2);
		contrainteRepos.save(c3);
		contrainteRepos.save(c4);
		contrainteRepos.save(c5);
		contrainteRepos.save(c6); 
		
		//Insérer des utilisateurs
		Utilisateur u1 = new Utilisateur (null, "bibi", "juju", "bibijuju","bibijuju@example.fr", "123", "3 avenue des Coquelicots, 35000 Rennes", LocalDate.of(2000, 3, 27),null ,  Arrays.asList(c1, c6));
		Utilisateur u2 = new Utilisateur (null, "bobo", "jojo", "bobojojo","bobojojo@example.fr", "123", "13 avenue des Peupliers, 57000 Metz",  LocalDate.of(1998, 3, 18), null ,Arrays.asList(c6));
		Utilisateur u3 = new Utilisateur (null, "bibi", "jiji", "bibijiji","bibijiji@example.fr", "123", "28 avenue des Bananes, 78000 Versailles", LocalDate.of(1998, 12, 25), null,Arrays.asList(c2));
		Utilisateur u4 = new Utilisateur (null, "mama", "momo", "mamamomo","mamamomo@example.fr", "123", "2 avenue des champs, 57000 Metz", LocalDate.of(1987, 06, 18), null,Arrays.asList());
		Utilisateur u5 = new Utilisateur (null, "mumu", "gugu", "mumugugu","mumugugu@example.fr", "123", "28 Bd des lys, 57000 Metz", LocalDate.of(1995, 01, 22), null,Arrays.asList(c1));
		utilisateurRepos.save(u1);
		utilisateurRepos.save(u2);
		utilisateurRepos.save(u3);
		utilisateurRepos.save(u4);
		utilisateurRepos.save(u5);
		String ls = System.lineSeparator();
		//Insérer des recettes
		Recette r1 = new Recette(null,"Cuisses de poulet rôti asiatiques", "Facile", 4,  "55 minutes","https://assets.afcdn.com/recipe/20220311/129892_w640h486c1cx512cy341cxb1024cyb683.webp","&#11; ÉTAPE 1 : &#12; Salez, poivrez et saupoudrez les cuisses de 5 épices &#10; &#11; ÉTAPE 2 : &#12; Mélangez la sauce soja, le miel, le gingembre et les gousses d'ail écrasées. Faites-y mariner le poulet 1 nuit en retournant les morceaux de temps en temps. &#10; &#11; ÉTAPE 3 : &#12; Faites cuire les cuisses de poulet au barbecue, sous le grill, à la broche ou au four à 200°C (thermostat 6-7) pendant 45 min en les retournant et en arrosant souvent. &#10; &#11; ÉTAPE 4 : &#12; A servir avec du riz ou des nouilles sautées aux légumes.",u1);
		Recette r2 = new Recette(null,"Lasagnes à la bolognaise", "Moyen", 8,  "2 h 5 minutes","https://assets.afcdn.com/recipe/20220311/129892_w640h486c1cx512cy341cxb1024cyb683.webp","&#11; ÉTAPE 1 : &#12; Faire revenir gousses hachées d'ail et les oignons émincés dans un peu d'huile d'olive. &#10; &#11; ÉTAPE 2 : &#12; Ajouter la carotte et la branche de céleri hachée puis la viande et faire revenir le tout. &#10; &#11; ÉTAPE 3 : &#12; Au bout de quelques minutes, ajouter le vin rouge. Laisser cuire jusqu'à évaporation. &#10; &#11; ÉTAPE 4 : &#12; Ajouter la purée de tomates, l'eau et les herbes. Saler, poivrer, puis laisser mijoter à feu doux 45 minutes. &#10; &#11; ÉTAPE 5 : &#12; Préparer la béchamel : faire fondre 100 g de beurre. &#10; &#11; ÉTAPE 6 : &#12; Hors du feu, ajouter la farine d'un coup.&#10; &#11; ÉTAPE 7 : &#12; Remettre sur le feu et remuer avec un fouet jusqu'à l'obtention d'un mélange bien lisse. &#10; &#11; ÉTAPE 8 : &#12; Ajouter le lait peu à peu. &#10; &#11; ÉTAPE 9 : &#12; Remuer sans cesse, jusqu'à ce que le mélange s'épaississe. &#10; &#11; ÉTAPE 10 : &#12; Ensuite, parfumer avec la muscade, saler, poivrer. Laisser cuire environ 5 minutes, à feu très doux, en remuant. Réserver. &#10; &#11; ÉTAPE 11 : &#12; Préchauffer le four à 200°C (thermostat 6-7). Huiler le plat à lasagnes. Poser une fine couche de béchamel puis des feuilles de lasagnes, de la bolognaise, de la béchamel et du parmesan. Répéter l'opération 3 fois de suite. &#10; &#11; ÉTAPE 12 : &#12; Sur la dernière couche de lasagnes, ne mettre que de la béchamel et recouvrir de fromage râpé. Parsemer quelques noisettes de beurre. &#10; &#11; ÉTAPE 13 : &#12; Enfourner pour environ 25 minutes de cuisson. &#10; ÉTAPE 14 Déguster",u2);
		Recette r3 = new Recette(null,"Poulet à l'asiatique", "Facile", 4,  "25 minutes","https://assets.afcdn.com/recipe/20170309/54194_w640h486c1cx1224cy1170.webp","&#11; ÉTAPE 1 : &#12; Peler et émincer l'ail et l'oignon, râper le zeste de citron et mélanger le tout avec la pâte de curry. &#10; &#11; ÉTAPE 2 : &#12; Couper les blancs de poulet en gros cube, les faire revenir à feu vif dans l'huile. &#10; &#11; ÉTAPE 3 : &#12; Les retirer, et déglacer avec la sauce soja, laisser bouillir 1 min puis verser la moitié du lait de coco. &#10; &#11; ÉTAPE 4 : &#12; Incorporer le mélange curry et le reste de lait de coco et le sucre, saler et poivrer puis remettre le poulet 5 min à feu moyen. &#10; &#11; ÉTAPE 5 : &#12; Servir avec du riz basmati.",u3);
		Recette r4 = new Recette(null,"Blanquette de veau", "Facile", 4,  "2 h 15 minutes","https://assets.afcdn.com/recipe/20190529/93191_w1000h667c1cx4330cy2886cxb8660cyb5773.webp","&#11; ÉTAPE 1 : &#12; Faire revenir la viande dans un peu de beurre doux jusqu'à ce que les morceaux soient un peu dorés. &#10; &#11; ÉTAPE 2 : &#12; Saupoudrer de 2 cuillères de farine. Bien remuer. &#10; &#11; ÉTAPE 3 : &#12; Ajouter 2 ou 3 verres d'eau, les cubes de bouillon, le vin et remuer. Ajouter de l'eau si nécessaire pour couvrir. &#10; &#11; ÉTAPE 4 : &#12; Couper les carottes en rondelles et émincer les oignons puis les incorporer à la viande, ainsi que les champignons.&#10; &#11; ÉTAPE 5 : &#12; Laisser mijoter à feu très doux environ 1h30 à 2h00 en remuant. &#10; &#11; ÉTAPE 6 : &#12; Si nécessaire, ajouter de l'eau de temps en temps. &#10; &#11; ÉTAPE 7 : &#12; Dans un bol, bien mélanger la crème fraîche, le jaune d’oeuf et le jus de citron. Ajouter ce mélange au dernier moment, bien remuer et servir tout de suite.",u4);
		Recette r5 = new Recette(null,"Emincé de boeuf citronné façon asiatique", "Facile", 4,  "45 minutes","https://assets.afcdn.com/recipe/20141122/56427_w640h486c1cx968cy1296.webp","&#11; ÉTAPE 1 : &#12; Coupez le boeuf en fines lamelles. &#10; &#11; ÉTAPE 2 : &#12; Emincez l'oignon et l'ail, ciselez la ciboulette. &#10; &#11; ÉTAPE 3 : &#12; Mettez tous ces ingrédients dans un saladier avec 2 cuillères à soupe de sauce soja, le jus du citron et 2 cuillères à soupe d'huile d'olive. Poivrez, mais ne salez surtout pas (la sauce soja l'est assez). Mélangez bien et laissez mariner pendant au moins une demi-heure. &#10; &#11; ÉTAPE 4 : &#12;Pendant ce temps, préparez les légumes. Si vous utilisez des légumes frais, précuisez les haricots, le chou frisé les petits pois, les blettes dans l'eau bouillante salée, puis égouttez-les bien. Pas la peine de blanchir le chou chinois. &#10; &#11; ÉTAPE 5 : &#12; Coupez tous les légumes en lamelles ou en tronçons, puis faites-les revenir dans une poêle (ou un wok) avec un peu d'huile d'olive. &#10; &#11; ÉTAPE 6 : &#12; Lorsqu'ils sont presque cuits (environ 10 min), rajoutez la viande avec toute la marinade et prolongez la cuisson d'environ cinq minutes. &#10; &#11; ÉTAPE 7 : &#12; Servez chaud.",u5);
		Recette r6 = new Recette(null,"Soupe asiatique aux crevettes et à la coriandre", "Facile", 4,  "26 minutes","https://assets.afcdn.com/recipe/20150204/28319_w1000h1208c1cx1250cy1509.webp","&#11; ÉTAPE 1 : &#12; Décortiquer les crevettes ; les réserver au frais.&#10; &#11; ÉTAPE 2 : &#12; Peler et hacher les échalotes, le gingembre, et les gousses d'ail.&#10; &#11; ÉTAPE 3 : &#12; Dans une sauteuse mettre une cuillère d'huile et faire suer les aromates.&#10; &#11; ÉTAPE 4 : &#12; Verser le lait de coco et le bouillon. Porter à ébullition et ajouter les pois gourmands effilés. Laisser cuire 4 mn.&#10; &#11; ÉTAPE 5 : &#12; Au moment de servir, ajouter les crevettes, le jus de citron et les brins de coriandre. Laisser frémir 2 mn et saler.&#10; &#11; ÉTAPE 6 : &#12; Servir aussitôt.",u1);
		Recette r7 = new Recette(null,"Poulet au four simple et savoureux", "Facile", 8,  "1 h 55 minutes","https://assets.afcdn.com/recipe/20200408/109519_w1000h1500c1cx1933cy2466cxb3744cyb5616.webp","&#11; ÉTAPE 1 : &#12; Préchauffer le four à 200°C (thermostat 6). Placer à l'intérieur du poulet deux gousses d'ail et les feuilles de laurier. &#10; &#11; ÉTAPE 2 : &#12; Préparer la sauce en mélangeant le jus de citron et le verre de bouillon de volaille. Arroser copieusement le poulet et verser le reste du jus dans le plat. &#10; &#11; ÉTAPE 3 : &#12; Saupoudrer le gros sel sur le poulet.&#10; &#11; ÉTAPE 4 : &#12; Placer le poulet dans le plat, avec les oignons coupés en quatre et les tomates cerises. &#10; &#11; ÉTAPE 5 : &#12; Placer le poulet au four durant environ 1 heure 40 à 200°C. (Au bout de 20 min de cuisson, retourner le poulet et laisser cuire 20 min, puis le replacer à l'endroit pour la suite de la cuisson) &#10; &#11; ÉTAPE 6 : &#12; Attention : Arroser le poulet avec son jus le plus souvent possible durant la cuisson (ajouter de l'eau si nécessaire). Le poulet n'en sera que plus moelleux ! &#10; &#11; ÉTAPE 7 : &#12; Récupérer le jus à la fin de la cuisson, avec les tomates et les oignons, dans un bol, et placer sur la table, avec une belle salade verte et une poêlée de pommes de terres nouvelles.",u2);
		Recette r8 = new Recette(null,"Boeuf bourguignon", "Facile", 4,  "5 heures","https://assets.afcdn.com/recipe/20220707/133382_w1000h641c1cx1396cy931cxb2162cyb1386.webp","&#11; ÉTAPE 1 : &#12; Détailler la viande en cubes de 3 cm de côté, enlever les gros morceaux de gras. &#10; &#11; ÉTAPE 2 : &#12; Couper l'oignon en morceaux. Le faire revenir dans une poêle au beurre. Une fois transparent, le verser dans une cocotte en fonte de préférence. &#10; &#11; ÉTAPE 3 : &#12; Procéder de même avec la viande mais en plusieurs fois, jusqu'à ce que tous les morceaux soient cuits. Les ajouter au fur et à mesure dans la cocotte. Ne pas avoir peur d'ajouter du beurre entre chaque fournée. &#10; &#11; ÉTAPE 4 : &#12; Quand toute la viande est dans la cocotte, déglacer la poêle avec de l'eau ou du vin et faire bouillir en raclant pour récupérer le suc. Saler, poivrer, ajouter au reste. &#10; &#11; ÉTAPE 5 : &#12; Recouvrir le tout avec une partie du vin et faire mijoter quelques heures avec le bouquet garni et les carottes en rondelles. &#10; &#11; ÉTAPE 6 : &#12; Le lendemain, faire mijoter au moins 2 heures en plusieurs fois, ajouter du vin ou de l'eau si nécessaire.",u3);
		Recette r9 = new Recette(null,"Chili con carne", "Facile", 4,  "35 minutes","https://assets.afcdn.com/recipe/20211222/126214_w1000h668c1cx1124cy721cxb2119cyb1415.webp","&#11; ÉTAPE 1 : &#12; Préchauffer le four à 180°C (thermostat 6). &#10; &#11; ÉTAPE 2 : &#12; Hacher l'oignon et l'ail. &#10; &#11; ÉTAPE 3 : &#12; Dans une cocotte en fonte, faire fondre le beurre, et ensuite dorer doucement l'oignon et l’ail. &#10; &#11; ÉTAPE 4 : &#12; Incorporer le boeuf haché et laisser cuire doucement 10 min. &#10; &#11; ÉTAPE 5 : &#12; Mélanger le chili, le cumin, le concentré de tomates, et incorporer le tout au boeuf. Ajouter les haricots, le bouillon, du sel et du poivre. &#10; &#11; ÉTAPE 6 : &#12; Couvrir et cuire 25 min au four.",u4);
		Recette r10 = new Recette(null,"Osso-bucco aux saveurs asiatiques façon funambuline", "Facile", 2,  "1 h 20 minutes","https://assets.afcdn.com/recipe/20100120/58727_w640h486c1cx192cy256.webp","&#11; ÉTAPE 1 : &#12; Mélanger tous les ingrédients de la marinade dans une assiette creuse. Y ajouter les rouelles d’osso-bucco. L’idéal, c’est de faire mariner le plus longtemps possible (1 nuit c'est idéal), évidemment, mais 1h de chaque côté c’est déjà pas mal. &#10; &#11; ÉTAPE 2 : &#12; Egoutter les rouelles et les fariner légèrement (tapoter pour enlever l’excès de farine). &#10; &#11; ÉTAPE 3 : &#12; Faire chauffer de l’huile dans votre plus jolie cocotte (vous savez, celle où c’est toujours meilleur quand vous cuisinez à l’intérieur). Y faire revenir vos rouelles à feu vif. Ajouter oignon, ail et légumes et faire revenir rapidement. &#10; &#11; ÉTAPE 4 : &#12; Déglacer avec la marinade, baisser le feu, ajouter le lait de coco, il faut que tout soit bien recouvert. Laisser mijoter le plus longtemps possible (au minimum 1h30), jusqu’à avoir la consistance de sauce qui vous plaise (si ça réduit trop vite, ajouter de l’eau). &#10; &#11; ÉTAPE 5 : &#12; Servir avec du riz blanc parfumé et saupoudrer de coriandre fraîche (ou à défaut de ciboulette).",u5);
		Recette r11 = new Recette(null,"Soupe de potimarron à l'asiatique", "Facile", 6,  "40 minutes","https://assets.afcdn.com/recipe/20131121/30224_w640h486c1cx1137cy851cxb2336cyb1762.webp","&#11; ÉTAPE 1 : &#12; Couper le potimarron, peau comprise, en gros morceaux et peler la pomme de terre. &#10; &#11; ÉTAPE 2 : &#12; Dans un peu d'huile, faire revenir les gousses d'ail coupées en petits morceaux. &#10; &#11; ÉTAPE 3 : &#12; Ajouter la pomme de terre, le potimarron, toutes les épices, sauf le curry et la noix de coco, l'eau et les cubes de bouillon. &#10; &#11; ÉTAPE 4 : &#12; Laisser cuire 20 minutes. &#10; &#11; ÉTAPE 5 : &#12; Mixer le tout. &#10; &#11; ÉTAPE 6 : &#12; Ajouter de l'eau si nécessaire, épicer avec du curry. &#10; &#11; ÉTAPE 7 : &#12; On peut ajouter du lait de coco, mais je trouve que le potimarron a un si bon goût, qu'il couvre la noix de coco.",u1);
		Recette r12 = new Recette(null,"Couscous poulet et merguez", "Facile", 6,  "1 h 5 minutes","https://assets.afcdn.com/recipe/20180621/79724_w1000h1333c1cx1944cy2592cxb3888cyb5184.webp","&#11; ÉTAPE 1 : &#12; Lavez et épluchez les carottes, les navets et les tomates et les couper en cubes. &#10; &#11; ÉTAPE 2 : &#12; Dans un autocuiseur, versez 3 cuillères à soupe d'huile d'olive. Mettez à chauffer et faites-y dorer les pilons de poulet. Quand ils sont dorés, versez l'équivalent d'1 litre d'eau et ajouter les cubes de bouillon de boeuf, le concentré de tomate, les carottes, navets et tomates, les épices à couscous et l'harissa. &#10; &#11; ÉTAPE 3 : &#12; Fermez votre autocuiseur et compter 25 mn de cuisson une fois que celui-ci est monté en pression. &#10; &#11; ÉTAPE 4 : &#12; En attendant, lavez et coupez les courgettes en cubes et égouttez les pois chiches. &#10; &#11; ÉTAPE 5 : &#12; Une fois les 25 mn écoulées, évacuez la vapeur de votre autocuiseur, ouvrez et rajouter les courgettes et les pois chiches. &#10; &#11; ÉTAPE 6 : &#12; Remettez au feu : comptez 10 mn de cuisson une fois votre autocuiseur sous pression.&#10; &#11; ÉTAPE 7 : &#12; Faites cuire vos merguez sur un grill ou à la poêle, mais pas avec les légumes. &#10; &#11; ÉTAPE 8 : &#12; Servez accompagné d'une semoule fine.",u2);
		Recette r13 = new Recette(null,"Wok de poulet poivron à l'asiatique", "Moyen", 4,  "1 h 15 minutes","https://assets.afcdn.com/recipe/20161004/23108_w640h486c1cx1500cy1000.webp","&#11; ÉTAPE 1 : &#12; Découper les poivrons en dés, le poulet en morceaux, et hacher finement l'ail et le gingembre.&#10; &#11; ÉTAPE 2 : &#12; Dans une jatte, placer les morceaux de poulet, l'ail, le gingembre, 2 cuillères à soupe de sauce soja et le jus d'un citron et demi.&#10; &#11; ÉTAPE 3 : &#12; Faire mariner au moins une demi heure. &#10; &#11; ÉTAPE 4 : &#12; Dans un wok, faire cuire les poivrons à feu doux (7 min). Réserver. &#10; &#11; ÉTAPE 5 : &#12; Pendant ce temps faire cuire le riz (idéal à l'étouffé, le riz doit être encore légèrement croquant mais cuit).&#10; &#11; ÉTAPE 6 : &#12; Ensuite saisir la marinade de poulet à feu vif pendant seulement deux à trois minutes (ainsi le poulet est doré à l'extérieur et fondant à l'intérieur). &#10; &#11; ÉTAPE 7 : &#12; Ensuite, faire sauter tous les ingrédients ensemble pendant 5 minutes en ajoutant une cuillère à soupe de soja. Au dernier moment ajouter la coriandre hachée et le jus du demi citron restant. &#10; &#11; ÉTAPE 8 : &#12; A servir immédiatement !",u3);
		Recette r14 = new Recette(null,"Poulet carottes-poivron à l'asiatique", "Facile", 2,  "50 minutes","https://assets.afcdn.com/recipe/20160820/33359_w640h486c1cx1150cy920.webp","&#11; ÉTAPE 1 : &#12; Commencez par râper les carottes grossièrement (grosse grille). &#10; &#11; ÉTAPE 2 : &#12; Émincez l'oignon, la gousse d'ail et le poivron en fines lamelles. &#10; &#11; ÉTAPE 3 : &#12; Dans une sauteuse, faites revenir les carottes et l'oignon dans de l'huile de sésame. &#10; &#11; ÉTAPE 4 : &#12; Pendant ce temps, coupez le poulet en petits morceaux. &#10; &#11; ÉTAPE 5 : &#12; Environ 10 minutes plus tard, ajoutez le poivron et les épices de votre choix. &#10; &#11; ÉTAPE 6 : &#12; Encore 10 minutes plus tard, ajoutez le poulet, et après 5 minutes de cuisson, le lait de coco, qui gardera votre poulet bien moelleux. &#10; &#11; ÉTAPE 7 : &#12; A la fin de la cuisson, ajoutez de la sauce soja. C'est un produit très salé, il faut donc y aller mollo et goûter au fur et à mesure. &#10; &#11; ÉTAPE 8 : &#12; Les temps de cuisson sont approximatifs, certains préféreront du croquant, d'autres du fondant. &#10; &#11; ÉTAPE 9 : &#12; Le mieux est donc toujours de goûter ! &#10; ",u4);
		Recette r15 = new Recette(null,"Emincés de dinde façon Asiatique", "Facile", 4,  "20 minutes","https://assets.afcdn.com/recipe/20170407/51254_w640h486c1cx1872cy2808.webp","&#11; ÉTAPE 1 : &#12; Émincer les escalopes en fines lamelles, les mélanger avec les autres ingrédients dans un saladier, recouvrir de papier film et laisser mariner 15 à 30 min au frigo. &#10; &#11; ÉTAPE 2 : &#12; Faire cuire environ 10 min dans une poêle chaude anti-adhésive. &#10; &#11; ÉTAPE 3 : &#12; Et c'est tout !",u5);
		Recette r16 = new Recette(null,"Crevettes marinées sautées à l'asiatique", "Facile", 4,  "25 minutes","https://assets.afcdn.com/recipe/20150219/8927_w640h486c1cx918cy1632.webp","&#11; ÉTAPE 1 : &#12; Préparer le fond de poêle en écrasant la gousse d'ail dans un ramequin. &#10; &#11; ÉTAPE 2 : &#12; Y ajouter le gingembre, l'huile d'olive, la sauce soja et le miel, bien mélanger et laisser reposer au moins une heure pour que les arômes se dégagent. &#10; &#11; ÉTAPE 3 : &#12; Verser la préparation dans une poêle ou un wok et faire chauffer jusqu'aux premiers frémissements &#10; &#11; ÉTAPE 4 : &#12; Ajouter alors les crevettes et faire revenir à feu vif jusqu'à la caramélisation souhaitée. &#10; ÉTAPE 5  : Accompagnements : &#10; - avec des nouilles chinoises préalablement cuites à l'eau puis revenues dans la poêle avec les crevettes en fin de cuisson (et/ou avec un chop suey de légumes). &#10;  - chaudes sur une salade de mâche, avocat, pamplemousse, champignons de paris crus émincés, vinaigre balsamique (pour une entrée par exemple)",u1);
		Recette r17 = new Recette(null,"Vinaigrette asiatique (pour salade de choux)", "Facile", 3,  "5 minutes","https://assets.afcdn.com/recipe/20141126/41490_w640h486c1cx1632cy1224.webp","&#11; ÉTAPE 1 : &#12; Mettre le vinaigre et le sucre avec le miel, et bien mélanger afin que le vinaigre dissolve le sucre peu à peu. &#10; &#11; ÉTAPE 2 : &#12; Ajouter les autres ingrédients, l'ordre n’a plus aucune importance. Saler et poivrer selon le goût. &#10;&#11; ÉTAPE 3 : &#12; Goutter la vinaigrette, elle doit à la fois être acidulée par le vinaigre et sucrée par le miel et le sucre. &#10; &#11; ÉTAPE 4 : &#12; Attention : l’huile de sésame possède un goût assez prononcé, la verser au goutte à goutte!",u2);
		Recette r18 = new Recette(null,"Tartiflette", "Facile", 4,  "1 h 15 minutes","https://assets.afcdn.com/recipe/20160401/38946_w1000h667c1cx2690cy1793.webp","&#11; ÉTAPE 1 : &#12; Eplucher les pommes de terre, les couper en dés, bien les rincer et les essuyer dans un torchon propre. &#10; &#11; ÉTAPE 2 : &#12; Faire chauffer l'huile dans une poêle, y faire fondre les oignons. &#10; &#11; ÉTAPE 3 : &#12; Lorsque les oignons sont fondus, ajouter les pommes de terre et les faire dorer de tous les côtés. &#10; &#11; ÉTAPE 4 : &#12; Lorsqu'elles sont dorées, ajouter les lardons et finir de cuire. Éponger le surplus de gras avec une feuille de papier essuie-tout. &#10; &#11; ÉTAPE 5 : &#12; D'autre part, gratter la croûte du reblochon et le couper en deux (ou en quatre). &#10; &#11; ÉTAPE 6 : &#12; Préchauffer le four à 200°C (thermostat 6-7) et préparer un plat à gratin en frottant le fond et les bords avec la gousse d'ail épluchée. &#10; &#11; ÉTAPE 7 : &#12; Dans le plat à gratin, étaler une couche de pommes de terre aux lardons, disposer dessus la moitié du reblochon, puis de nouveau des pommes de terre. Terminer avec le reste du reblochon (croûte vers les pommes de terre). &#10; &#11; ÉTAPE 8 : &#12; Enfourner pour environ 20 minutes de cuisson.",u3);
		Recette r19 = new Recette(null,"Fondue aux poireaux", "Facile", 4,  "1 h","https://assets.afcdn.com/recipe/20131027/10725_w600h400cx300cy200.webp","&#11; ÉTAPE 1 : &#12; Coupez les poireaux en deux et recoupez-les en tronçons. Lavez soigneusement. &#10; &#11; ÉTAPE 2 : &#12; Faites fondre le beurre dans une casserole, ajoutez les poireaux, mélangez, couvrez et faites cuire à feu très doux pendant 25 min environ, en remuant de temps en temps. &#10; &#11; ÉTAPE 3 : &#12; A ce moment là ajoutez le jus de citron, la moutarde et la crème aux poireaux, salez légèrement, poivrez et mélangez bien. &#10; &#11; ÉTAPE 4 : &#12; Couvrez et laissez cuire encore 10 min à feu doux.",u4);
		Recette r20 = new Recette(null,"Pâtes à la carbonara à la française", "Facile", 4,  "20 minutes","https://assets.afcdn.com/recipe/20211214/125831_w1000h1000c1cx866cy866cxb1732cyb1732.webp","&#11; ÉTAPE 1 : &#12; Cuire les pâtes dans un grand volume d'eau bouillante salée. &#10; &#11; ÉTAPE 2 : &#12; Emincer les oignons et les faire revenir à la poêle. Dès qu'ils ont bien dorés, y ajouter les lardons. &#10; &#11; ÉTAPE 3 : &#12; Préparer dans un saladier la crème fraîche, les oeufs, le sel, le poivre et mélanger. &#10; &#11; ÉTAPE 4 : &#12; Retirer les lardons du feu dès qu'ils sont dorés et les ajouter à la crème. &#10; &#11; ÉTAPE 5 : &#12; Une fois les pâtes cuite al dente, les égoutter et y incorporer la crème. Remettre sur le feu si le plat a refroidi. &#10; &#11; ÉTAPE 6 : &#12; Servir et bon appétit ! Vous pouvez également agrémenter votre plat avec des champignons.",u5);
		Recette r21 = new Recette(null,"Rôti de boeuf", "Facile", 2,  "30 minutes","https://assets.afcdn.com/recipe/20180621/79712_w1000h1333c1cx1944cy2592cxb3888cyb5184.webp","&#11; ÉTAPE 1 : &#12; Préchauffer le four à 220°C (thermostat 7-8). Mettre le rôti avec barde et ficelles dans un plat qui va au four. Couper la gousse d'ail en deux et en frotter le rôti. Parsemer le haut du rôti de thym et l'arroser d'huile d'olive. Poser les gousses d'ail sur le rôti. &#10; &#11; ÉTAPE 2 : &#12; Enfourner pour 15 minutes de cuisson. Sortir le rôti et retirer la barde et la ficelle. Ajouter l'eau et faire tomber l'ail dans le plat &#10; &#11; ÉTAPE 3 : &#12; Saler et poivrer à convenance le rôti. Laisser cuire 10 à 15 minutes au four selon la cuisson désirée.",u2);
		recetteRepos.save(r1);
		recetteRepos.save(r2);
		recetteRepos.save(r3);
		recetteRepos.save(r4);
		recetteRepos.save(r5);
		recetteRepos.save(r6);
		recetteRepos.save(r7);
		recetteRepos.save(r8);
		recetteRepos.save(r9);
		recetteRepos.save(r10);
		recetteRepos.save(r11);
		recetteRepos.save(r12);
		recetteRepos.save(r13);
		recetteRepos.save(r14);
		recetteRepos.save(r15);
		recetteRepos.save(r16);
		recetteRepos.save(r17);
		recetteRepos.save(r18);
		recetteRepos.save(r19);
		recetteRepos.save(r20);
		recetteRepos.save(r21);
		
		//Insérer des ingrédients recette
		IngredientRecette ir1 = new IngredientRecette(null,1, "cas", 4 ,r1, i56);
		IngredientRecette ir2 = new IngredientRecette(null,1, "cac", 4 ,r1, i34);
		IngredientRecette ir3 = new IngredientRecette(null,1, "cac", 4 ,r1, i41);
		IngredientRecette ir4 = new IngredientRecette(null,4, null, 4 ,r1, i1);
		IngredientRecette ir5 = new IngredientRecette(null,2, null, 4 ,r1, i2);
		IngredientRecette ir6 = new IngredientRecette(null,3, "cas", 4 ,r1, i82);
		IngredientRecette ir7 = new IngredientRecette(null,1, "paquet", 8 ,r2, i53);
		IngredientRecette ir8 = new IngredientRecette(null,3, null, 8 ,r2, i61);
		IngredientRecette ir9 = new IngredientRecette(null,1, null, 8 ,r2, i14);
		IngredientRecette ir10 = new IngredientRecette(null,800, "g", 8 ,r2, i78);
		IngredientRecette ir11 = new IngredientRecette(null,15, "cl", 8 ,r2, i32);
		IngredientRecette ir12 = new IngredientRecette(null,2, null, 8 ,r2, i38);
		IngredientRecette ir13 = new IngredientRecette(null,1, null, 8 ,r2, i84);
		IngredientRecette ir14 = new IngredientRecette(null,70, "g", 8 ,r2, i40);
		IngredientRecette ir15 = new IngredientRecette(null,125, "g", 8 ,r2, i64);
		IngredientRecette ir16 = new IngredientRecette(null,100, "g", 8 ,r2, i37);
		IngredientRecette ir17 = new IngredientRecette(null,125, "g", 8 ,r2, i4);
		IngredientRecette ir18 = new IngredientRecette(null,2, "gousse", 8 ,r2, i2);
		IngredientRecette ir19 = new IngredientRecette(null,1, "branche", 8 ,r2, i15);
		IngredientRecette ir20 = new IngredientRecette(null,600, "g", 8 ,r2, i8);
		IngredientRecette ir21 = new IngredientRecette(null,20, "cl", 8 ,r2, i88);
		IngredientRecette ir22 = new IngredientRecette(null,1, null, 8 ,r2, i3);
		IngredientRecette ir23 = new IngredientRecette(null,3, "pincee", 8 ,r2, i59);
		IngredientRecette ir24 = new IngredientRecette(null,1, "l", 8 ,r2, i50);
		IngredientRecette ir25  = new IngredientRecette(null,1, null, 4 ,r3, i62);
		IngredientRecette ir26 = new IngredientRecette(null,3, "cas", 4 ,r3, i45);
		IngredientRecette ir27 = new IngredientRecette(null,1, "pincee", 4 ,r3, i83);
		IngredientRecette ir28 = new IngredientRecette(null,4, null, 4 ,r3, i5);
		IngredientRecette ir29 = new IngredientRecette(null,2, "gousse", 4 ,r3, i2);
		IngredientRecette ir30 = new IngredientRecette(null,1, null, 4 ,r3, i19);
		IngredientRecette ir31 = new IngredientRecette(null,1, "cas", 4 ,r3, i65);
		IngredientRecette ir32 = new IngredientRecette(null,3, "cas", 4 ,r3, i82);
		IngredientRecette ir33 = new IngredientRecette(null,400, "g", 4 ,r3, i51);
		IngredientRecette ir34 = new IngredientRecette(null,1, "cube", 4 ,r4, i9);
		IngredientRecette ir35 = new IngredientRecette(null,2, null, 4 ,r4, i14);
		IngredientRecette ir36 = new IngredientRecette(null,1, null, 4 ,r4, i61);
		IngredientRecette ir37 = new IngredientRecette(null,1, "petit pot", 4 ,r4, i26);
		IngredientRecette ir38 = new IngredientRecette(null,1, null, 4 ,r4, i37);
		IngredientRecette ir39 = new IngredientRecette(null,1, "kg", 4 ,r4, i6);
		IngredientRecette ir40 = new IngredientRecette(null,1, null, 4 ,r4, i10);
		IngredientRecette ir41 = new IngredientRecette(null,1, "petite boite", 4 ,r4, i16);
		IngredientRecette ir42 = new IngredientRecette(null,1, null, 4 ,r4, i19);
		IngredientRecette ir43 = new IngredientRecette(null,1, null, 4 ,r4, i48);
		IngredientRecette ir44 = new IngredientRecette(null,25, "cl", 4 ,r4, i87);
		IngredientRecette ir45 = new IngredientRecette(null,2, "cas", 4 ,r5, i45);
		IngredientRecette ir46 = new IngredientRecette(null,1, null, 4 ,r5, i61);
		IngredientRecette ir47 = new IngredientRecette(null,400, "g", 4 ,r5, i7);
		IngredientRecette ir48 = new IngredientRecette(null,1, null, 4 ,r5, i19);
		IngredientRecette ir49 = new IngredientRecette(null,1, "bouquet", 4 ,r5, i18);
		IngredientRecette ir50 = new IngredientRecette(null,2, "cas", 4 ,r5, i81);
		IngredientRecette ir51 = new IngredientRecette(null,1, "gousse", 4 ,r5, i2);
		IngredientRecette ir52 = new IngredientRecette(null,400, "g ", 4 ,r5, i89);
		IngredientRecette ir53 = new IngredientRecette(null,2, null, 4 ,r6, i40);
		IngredientRecette ir54 = new IngredientRecette(null,40, "cl", 4 ,r6, i9);
		IngredientRecette ir55 = new IngredientRecette(null,4, "brins", 4 ,r6, i23);
		IngredientRecette ir56 = new IngredientRecette(null,500, "g", 4 ,r6, i26);
		IngredientRecette ir57 = new IngredientRecette(null,2, null, 4 ,r6, i32);
		IngredientRecette ir58 = new IngredientRecette(null,40, "cl", 4 ,r6, i50);
		IngredientRecette ir59 = new IngredientRecette(null,2, "gousse", 4 ,r6, i2);
		IngredientRecette ir60 = new IngredientRecette(null,100, "g", 4 ,r6, i70);
		IngredientRecette ir61 = new IngredientRecette(null,1, null, 4 ,r6, i20);
		IngredientRecette ir62 = new IngredientRecette(null,2, null, 8 ,r7, i61);
		IngredientRecette ir63 = new IngredientRecette(null,1, "poignee", 8 ,r7, i85);
		IngredientRecette ir64 = new IngredientRecette(null,1, null, 8 ,r7, i37);
		IngredientRecette ir65 = new IngredientRecette(null,1, null, 8 ,r7, i76);
		IngredientRecette ir66 = new IngredientRecette(null,3, "gousse", 8 ,r7, i2);
		IngredientRecette ir67 = new IngredientRecette(null,1, "cl de jus", 8 ,r7, i18);
		IngredientRecette ir68 = new IngredientRecette(null,1, null, 8 ,r7, i11);
		IngredientRecette ir69 = new IngredientRecette(null,4, null, 4 ,r8, i61);
		IngredientRecette ir70 = new IngredientRecette(null,4, null, 4 ,r8, i14);
		IngredientRecette ir71 = new IngredientRecette(null,100, "g", 4 ,r8, i4);
		IngredientRecette ir72 = new IngredientRecette(null,600, "g", 4 ,r8, i13);
		IngredientRecette ir73 = new IngredientRecette(null,1, null, 4 ,r8, i12);
		IngredientRecette ir74 = new IngredientRecette(null,1, "bouteille", 4 ,r8, i87);
		IngredientRecette ir75 = new IngredientRecette(null,50, "g", 4 ,r9, i4);
		IngredientRecette ir76 = new IngredientRecette(null,2, null, 4 ,r9, i61);
		IngredientRecette ir77 = new IngredientRecette(null,1, "cac", 4 ,r9, i17);
		IngredientRecette ir78 = new IngredientRecette(null,2, "cac", 4 ,r9, i29);
		IngredientRecette ir79 = new IngredientRecette(null,1, null, 4 ,r9, i42);
		IngredientRecette ir80 = new IngredientRecette(null,30, "cl", 4 ,r9, i90);
		IngredientRecette ir81 = new IngredientRecette(null,1, null, 4 ,r9, i91);
		IngredientRecette ir82 = new IngredientRecette(null,2, "gousse", 4 ,r9, i2);
		IngredientRecette ir83 = new IngredientRecette(null,500, "g", 4 ,r9, i8);
		IngredientRecette ir84 = new IngredientRecette(null,65, "g", 4 ,r9, i84);
		IngredientRecette ir85 = new IngredientRecette(null,1, null, 2 ,r10, i62);
		IngredientRecette ir86 = new IngredientRecette(null,1, null, 2 ,r10, i40);
		IngredientRecette ir87 = new IngredientRecette(null,1, "cac", 2 ,r10, i67);
		IngredientRecette ir88 = new IngredientRecette(null,1, "cac", 2 ,r10, i55);
		IngredientRecette ir89 = new IngredientRecette(null,1, null, 2 ,r10, i19);
		IngredientRecette ir90 = new IngredientRecette(null,1, "baton", 2 ,r10, i21);
		IngredientRecette ir91 = new IngredientRecette(null,1, "cac", 2 ,r10, i41);
		IngredientRecette ir92 = new IngredientRecette(null,1, "cac", 2 ,r10, i53);
		IngredientRecette ir93 = new IngredientRecette(null,44958, "cac", 2 ,r10, i58);
		IngredientRecette ir94 = new IngredientRecette(null,2, "cas", 2 ,r10, i81);
		IngredientRecette ir95 = new IngredientRecette(null,1, "cac", 6 ,r11, i23);
		IngredientRecette ir96 = new IngredientRecette(null,1, "cac", 6 ,r11, i28);
		IngredientRecette ir97 = new IngredientRecette(null,1, "cac", 6 ,r11, i40);
		IngredientRecette ir98 = new IngredientRecette(null,1, "l", 6 ,r11, i31);
		IngredientRecette ir99 = new IngredientRecette(null,2, "cube", 6 ,r11, i9);
		IngredientRecette ir100 = new IngredientRecette(null,1, "cac", 6 ,r11, i30);
		IngredientRecette ir101 = new IngredientRecette(null,1, "kg", 6 ,r11, i75);
		IngredientRecette ir102 = new IngredientRecette(null,2, "gousse", 6 ,r11, i2);
		IngredientRecette ir103 = new IngredientRecette(null,1, null, 6 ,r11, i74);
		IngredientRecette ir104 = new IngredientRecette(null,1, "branche", 6 ,r11, i21);
		IngredientRecette ir105 = new IngredientRecette(null,1, null, 6 ,r11, i50);
		IngredientRecette ir106 = new IngredientRecette(null,12, null, 6 ,r12, i54);
		IngredientRecette ir107 = new IngredientRecette(null,1, null, 6 ,r12, i45);
		IngredientRecette ir108 = new IngredientRecette(null,1, "cac", 6 ,r12, i43);
		IngredientRecette ir109 = new IngredientRecette(null,2, "cube", 6 ,r12, i90);
		IngredientRecette ir110 = new IngredientRecette(null,3, null, 6 ,r12, i84);
		IngredientRecette ir111 = new IngredientRecette(null,5, null, 6 ,r12, i14);
		IngredientRecette ir112 = new IngredientRecette(null,2, null, 6 ,r12, i24);
		IngredientRecette ir113 = new IngredientRecette(null,400, "g", 6 ,r12, i69);
		IngredientRecette ir114 = new IngredientRecette(null,8, null, 6 ,r12, i66);
		IngredientRecette ir115 = new IngredientRecette(null,2, "boite", 6 ,r12, i22);
		IngredientRecette ir116 = new IngredientRecette(null,3, "cas", 6 ,r12, i34);
		IngredientRecette ir117 = new IngredientRecette(null,10, null, 6 ,r12, i59);
		IngredientRecette ir118 = new IngredientRecette(null,1, null, 4 ,r13, i72);
		IngredientRecette ir119 = new IngredientRecette(null,1, null, 4 ,r13, i73);
		IngredientRecette ir120 = new IngredientRecette(null,1, "cas", 4 ,r13, i40);
		IngredientRecette ir121 = new IngredientRecette(null,44958, "botte", 4 ,r13, i23);
		IngredientRecette ir122 = new IngredientRecette(null,4, null, 4 ,r13, i5);
		IngredientRecette ir123 = new IngredientRecette(null,300, "g", 4 ,r13, i79);
		IngredientRecette ir124 = new IngredientRecette(null,2, null, 4 ,r13, i18);
		IngredientRecette ir125 = new IngredientRecette(null,3, "gousse", 4 ,r13, i2);
		IngredientRecette ir126 = new IngredientRecette(null,3, "cas", 4 ,r13, i81);
		IngredientRecette ir127 = new IngredientRecette(null,4, null, 2 ,r14, i14);
		IngredientRecette ir128 = new IngredientRecette(null,1, null, 2 ,r14, i71);
		IngredientRecette ir129 = new IngredientRecette(null,1, null, 2 ,r14, i61);
		IngredientRecette ir130 = new IngredientRecette(null,1, "cas", 2 ,r14, i46);
		IngredientRecette ir131 = new IngredientRecette(null,2, null, 2 ,r14, i1);
		IngredientRecette ir132 = new IngredientRecette(null,1, null, 2 ,r14, i2);
		IngredientRecette ir133 = new IngredientRecette(null,4, "cas", 2 ,r14, i81);
		IngredientRecette ir134 = new IngredientRecette(null,10, "cl", 2 ,r14, i50);
		IngredientRecette ir135 = new IngredientRecette(null,1, null, 2 ,r14, i33);
		IngredientRecette ir136 = new IngredientRecette(null,2, "cas", 4 ,r15, i55);
		IngredientRecette ir137 = new IngredientRecette(null,1, "cas", 4 ,r15, i44);
		IngredientRecette ir138 = new IngredientRecette(null,350, "g", 4 ,r15, i35);
		IngredientRecette ir139 = new IngredientRecette(null,1, null, 4 ,r15, i19);
		IngredientRecette ir140 = new IngredientRecette(null,1, null, 4 ,r15, i2);
		IngredientRecette ir141 = new IngredientRecette(null,3, "cas", 4 ,r15, i81);
		IngredientRecette ir142 = new IngredientRecette(null,1, "cas", 4 ,r16, i40);
		IngredientRecette ir143 = new IngredientRecette(null,3, "cas", 4 ,r16, i45);
		IngredientRecette ir144 = new IngredientRecette(null,2, "cas", 4 ,r16, i55);
		IngredientRecette ir145 = new IngredientRecette(null,800, "g", 4 ,r16, i26);
		IngredientRecette ir146 = new IngredientRecette(null,1, null, 4 ,r16, i2);
		IngredientRecette ir147 = new IngredientRecette(null,3, "cas", 4 ,r16, i81);
		IngredientRecette ir148 = new IngredientRecette(null,1, "cac", 3 ,r17, i82);
		IngredientRecette ir149 = new IngredientRecette(null,2, "cac", 3 ,r17, i55);
		IngredientRecette ir150 = new IngredientRecette(null,6, "cac", 3 ,r17, i45);
		IngredientRecette ir151 = new IngredientRecette(null,1, "cac", 3 ,r17, i88);
		IngredientRecette ir152 = new IngredientRecette(null,4, "gouttes", 3 ,r17, i46);
		IngredientRecette ir153 = new IngredientRecette(null,1, "cac", 3 ,r17, i56);
		IngredientRecette ir154 = new IngredientRecette(null,200, "g", 4 ,r18, i61);
		IngredientRecette ir155 = new IngredientRecette(null,1, null, 4 ,r18, i78);
		IngredientRecette ir156 = new IngredientRecette(null,2, "cas", 4 ,r18, i44);
		IngredientRecette ir157 = new IngredientRecette(null,1, "kg", 4 ,r18, i74);
		IngredientRecette ir158 = new IngredientRecette(null,200, "g", 4 ,r18, i51);
		IngredientRecette ir159 = new IngredientRecette(null,1, null, 4 ,r18, i2);
		IngredientRecette ir160 = new IngredientRecette(null,600, "g", 4 ,r19, i68);
		IngredientRecette ir161 = new IngredientRecette(null,30, "g", 4 ,r19, i4);
		IngredientRecette ir162 = new IngredientRecette(null,1, "cas", 4 ,r19, i57);
		IngredientRecette ir163 = new IngredientRecette(null,2, "cas", 4 ,r19, i25);
		IngredientRecette ir164 = new IngredientRecette(null,2, "jus cas", 4 ,r19, i48);
		IngredientRecette ir165 = new IngredientRecette(null,50, "cl", 4 ,r20, i25);
		IngredientRecette ir166 = new IngredientRecette(null,250, "g", 4 ,r20, i51);
		IngredientRecette ir167 = new IngredientRecette(null,1, null, 4 ,r20, i61);
		IngredientRecette ir168 = new IngredientRecette(null,500, "g", 4 ,r20, i65);
		IngredientRecette ir169 = new IngredientRecette(null,3, null, 4 ,r20, i47);
		IngredientRecette ir170 = new IngredientRecette(null,4, null, 4 ,r21, i61);
		IngredientRecette ir171 = new IngredientRecette(null,4, null, 4 ,r21, i14);
		IngredientRecette ir172 = new IngredientRecette(null,100, "g", 4 ,r21, i4);
		IngredientRecette ir173 = new IngredientRecette(null,600, "g", 4 ,r21, i13);
		IngredientRecette ir174 = new IngredientRecette(null,1, null, 4 ,r21, i12);
		IngredientRecette ir175 = new IngredientRecette(null,1, "bouteille", 4 ,r21, i87);
		ingredientRecetteRepos.save(ir1);
		ingredientRecetteRepos.save(ir2);
		ingredientRecetteRepos.save(ir3);
		ingredientRecetteRepos.save(ir4);
		ingredientRecetteRepos.save(ir5);
		ingredientRecetteRepos.save(ir6);
		ingredientRecetteRepos.save(ir7);
		ingredientRecetteRepos.save(ir8);
		ingredientRecetteRepos.save(ir9);
		ingredientRecetteRepos.save(ir10);
		ingredientRecetteRepos.save(ir11);
		ingredientRecetteRepos.save(ir12);
		ingredientRecetteRepos.save(ir13);
		ingredientRecetteRepos.save(ir14);
		ingredientRecetteRepos.save(ir15);
		ingredientRecetteRepos.save(ir16);
		ingredientRecetteRepos.save(ir17);
		ingredientRecetteRepos.save(ir18);
		ingredientRecetteRepos.save(ir19);
		ingredientRecetteRepos.save(ir20);
		ingredientRecetteRepos.save(ir21);
		ingredientRecetteRepos.save(ir22);
		ingredientRecetteRepos.save(ir23);
		ingredientRecetteRepos.save(ir24);
		ingredientRecetteRepos.save(ir25);
		ingredientRecetteRepos.save(ir26);
		ingredientRecetteRepos.save(ir27);
		ingredientRecetteRepos.save(ir28);
		ingredientRecetteRepos.save(ir29);
		ingredientRecetteRepos.save(ir30);
		ingredientRecetteRepos.save(ir31);
		ingredientRecetteRepos.save(ir32);
		ingredientRecetteRepos.save(ir33);
		ingredientRecetteRepos.save(ir34);
		ingredientRecetteRepos.save(ir35);
		ingredientRecetteRepos.save(ir36);
		ingredientRecetteRepos.save(ir37);
		ingredientRecetteRepos.save(ir38);
		ingredientRecetteRepos.save(ir39);
		ingredientRecetteRepos.save(ir40);
		ingredientRecetteRepos.save(ir41);
		ingredientRecetteRepos.save(ir42);
		ingredientRecetteRepos.save(ir43);
		ingredientRecetteRepos.save(ir44);
		ingredientRecetteRepos.save(ir45);
		ingredientRecetteRepos.save(ir46);
		ingredientRecetteRepos.save(ir47);
		ingredientRecetteRepos.save(ir48);
		ingredientRecetteRepos.save(ir49);
		ingredientRecetteRepos.save(ir50);
		ingredientRecetteRepos.save(ir51);
		ingredientRecetteRepos.save(ir52);
		ingredientRecetteRepos.save(ir53);
		ingredientRecetteRepos.save(ir54);
		ingredientRecetteRepos.save(ir55);
		ingredientRecetteRepos.save(ir56);
		ingredientRecetteRepos.save(ir57);
		ingredientRecetteRepos.save(ir58);
		ingredientRecetteRepos.save(ir59);
		ingredientRecetteRepos.save(ir60);
		ingredientRecetteRepos.save(ir61);
		ingredientRecetteRepos.save(ir62);
		ingredientRecetteRepos.save(ir63);
		ingredientRecetteRepos.save(ir64);
		ingredientRecetteRepos.save(ir65);
		ingredientRecetteRepos.save(ir66);
		ingredientRecetteRepos.save(ir67);
		ingredientRecetteRepos.save(ir68);
		ingredientRecetteRepos.save(ir69);
		ingredientRecetteRepos.save(ir70);
		ingredientRecetteRepos.save(ir71);
		ingredientRecetteRepos.save(ir72);
		ingredientRecetteRepos.save(ir73);
		ingredientRecetteRepos.save(ir74);
		ingredientRecetteRepos.save(ir75);
		ingredientRecetteRepos.save(ir76);
		ingredientRecetteRepos.save(ir77);
		ingredientRecetteRepos.save(ir78);
		ingredientRecetteRepos.save(ir79);
		ingredientRecetteRepos.save(ir80);
		ingredientRecetteRepos.save(ir81);
		ingredientRecetteRepos.save(ir82);
		ingredientRecetteRepos.save(ir83);
		ingredientRecetteRepos.save(ir84);
		ingredientRecetteRepos.save(ir85);
		ingredientRecetteRepos.save(ir86);
		ingredientRecetteRepos.save(ir87);
		ingredientRecetteRepos.save(ir88);
		ingredientRecetteRepos.save(ir89);
		ingredientRecetteRepos.save(ir90);
		ingredientRecetteRepos.save(ir91);
		ingredientRecetteRepos.save(ir92);
		ingredientRecetteRepos.save(ir93);
		ingredientRecetteRepos.save(ir94);
		ingredientRecetteRepos.save(ir95);
		ingredientRecetteRepos.save(ir96);
		ingredientRecetteRepos.save(ir97);
		ingredientRecetteRepos.save(ir98);
		ingredientRecetteRepos.save(ir99);
		ingredientRecetteRepos.save(ir100);
		ingredientRecetteRepos.save(ir101);
		ingredientRecetteRepos.save(ir102);
		ingredientRecetteRepos.save(ir103);
		ingredientRecetteRepos.save(ir104);
		ingredientRecetteRepos.save(ir105);
		ingredientRecetteRepos.save(ir106);
		ingredientRecetteRepos.save(ir107);
		ingredientRecetteRepos.save(ir108);
		ingredientRecetteRepos.save(ir109);
		ingredientRecetteRepos.save(ir110);
		ingredientRecetteRepos.save(ir111);
		ingredientRecetteRepos.save(ir112);
		ingredientRecetteRepos.save(ir113);
		ingredientRecetteRepos.save(ir114);
		ingredientRecetteRepos.save(ir115);
		ingredientRecetteRepos.save(ir116);
		ingredientRecetteRepos.save(ir117);
		ingredientRecetteRepos.save(ir118);
		ingredientRecetteRepos.save(ir119);
		ingredientRecetteRepos.save(ir120);
		ingredientRecetteRepos.save(ir121);
		ingredientRecetteRepos.save(ir122);
		ingredientRecetteRepos.save(ir123);
		ingredientRecetteRepos.save(ir124);
		ingredientRecetteRepos.save(ir125);
		ingredientRecetteRepos.save(ir126);
		ingredientRecetteRepos.save(ir127);
		ingredientRecetteRepos.save(ir128);
		ingredientRecetteRepos.save(ir129);
		ingredientRecetteRepos.save(ir130);
		ingredientRecetteRepos.save(ir131);
		ingredientRecetteRepos.save(ir132);
		ingredientRecetteRepos.save(ir133);
		ingredientRecetteRepos.save(ir134);
		ingredientRecetteRepos.save(ir135);
		ingredientRecetteRepos.save(ir136);
		ingredientRecetteRepos.save(ir137);
		ingredientRecetteRepos.save(ir138);
		ingredientRecetteRepos.save(ir139);
		ingredientRecetteRepos.save(ir140);
		ingredientRecetteRepos.save(ir141);
		ingredientRecetteRepos.save(ir142);
		ingredientRecetteRepos.save(ir143);
		ingredientRecetteRepos.save(ir144);
		ingredientRecetteRepos.save(ir145);
		ingredientRecetteRepos.save(ir146);
		ingredientRecetteRepos.save(ir147);
		ingredientRecetteRepos.save(ir148);
		ingredientRecetteRepos.save(ir149);
		ingredientRecetteRepos.save(ir150);
		ingredientRecetteRepos.save(ir151);
		ingredientRecetteRepos.save(ir152);
		ingredientRecetteRepos.save(ir153);
		ingredientRecetteRepos.save(ir154);
		ingredientRecetteRepos.save(ir155);
		ingredientRecetteRepos.save(ir156);
		ingredientRecetteRepos.save(ir157);
		ingredientRecetteRepos.save(ir158);
		ingredientRecetteRepos.save(ir159);
		ingredientRecetteRepos.save(ir160);
		ingredientRecetteRepos.save(ir161);
		ingredientRecetteRepos.save(ir162);
		ingredientRecetteRepos.save(ir163);
		ingredientRecetteRepos.save(ir164);
		ingredientRecetteRepos.save(ir165);
		ingredientRecetteRepos.save(ir166);
		ingredientRecetteRepos.save(ir167);
		ingredientRecetteRepos.save(ir168);
		ingredientRecetteRepos.save(ir169);
		ingredientRecetteRepos.save(ir170);
		ingredientRecetteRepos.save(ir171);
		ingredientRecetteRepos.save(ir172);
		ingredientRecetteRepos.save(ir173);
		ingredientRecetteRepos.save(ir174);
		ingredientRecetteRepos.save(ir175);
		
		//Création liste de course
		ListeCourse lc1 = new ListeCourse(null,"Ma liste de course", null, null, u1,true);
		ListeCourse lc2 = new ListeCourse(null,"Ma liste de course", null, null, u2,false);
		ListeCourse lc3 = new ListeCourse(null,"Ma liste de course", null, null, u3, false);
		ListeCourse lc4 = new ListeCourse(null,"Ma liste de course", null, null, u4, false);
		ListeCourse lc5 = new ListeCourse(null,"Ma liste de course", null, null, u5, false);
		ListeCourse lc6 = new ListeCourse(null,"Ma 2e liste de course", null, null, u1,false);
		listeCourseRepos.save(lc1);
		listeCourseRepos.save(lc2);
		listeCourseRepos.save(lc3);
		listeCourseRepos.save(lc4);
		listeCourseRepos.save(lc5);
		listeCourseRepos.save(lc6);
		
		//Creation ingredient course
		
		IngredientCourse ic4 = new IngredientCourse(null, 2, null, true, false,  lc1, i75, u1);
		IngredientCourse ic1 = new IngredientCourse(null, 2, null, true, false,  lc1, i71, u1);
		IngredientCourse ic2 = new IngredientCourse(null, 2, null, true, false,  lc1, i73, u1);
		IngredientCourse ic3 = new IngredientCourse(null, 1, "kg", true, false,  lc1, i8, u1);
		IngredientCourse ic5 = new IngredientCourse(null, 1, "kg", true, false,  lc1, i6, u1);
		IngredientCourse ic6 = new IngredientCourse(null, 2, "cube", true, false,  lc1, i9, u1);
		IngredientCourse ic7 = new IngredientCourse(null, 2, null, true, false,  lc1, i10, u1);
		IngredientCourse ic8 = new IngredientCourse(null, 800, "g", true, false,  lc1, i78, u1);
		IngredientCourse ic9 = new IngredientCourse(null, 700, "g", true, false,  lc1, i7, u1);
		IngredientCourse ic10 = new IngredientCourse(null, 2, null, true, false,  lc1, i12, u1);
		IngredientCourse ic11 = new IngredientCourse(null, 2, null, true, false,  lc1, i25, u1);
		IngredientCourse ic12 = new IngredientCourse(null, 2, null, true, false,  lc1, i50, u1);
		IngredientCourse ic13 = new IngredientCourse(null, 700, "g", true, false,  lc1, i7, u1);
		IngredientCourse ic14 = new IngredientCourse(null, 2, null, true, false,  lc1, i12, u1);
		IngredientCourse ic15 = new IngredientCourse(null, 2, null, true, false,  lc1, i25, u1);
		IngredientCourse ic16 = new IngredientCourse(null, 2, null, true, false,  lc1, i50, u1);
		
		IngredientCourse ic17 = new IngredientCourse(null, 1, null, true, false,  lc2, i49, u2);
		IngredientCourse ic18 = new IngredientCourse(null, 2, null, true, false,  lc2, i60, u2);
		IngredientCourse ic19 = new IngredientCourse(null, 3, null, true, false,  lc2, i67, u2);
		IngredientCourse ic20 = new IngredientCourse(null, 1, null, true, false,  lc2, i55, u2);
		
		ingredientCourseRepos.save(ic4);
		ingredientCourseRepos.save(ic1);
		ingredientCourseRepos.save(ic2);
		ingredientCourseRepos.save(ic3);
		ingredientCourseRepos.save(ic5);
		ingredientCourseRepos.save(ic6);
		ingredientCourseRepos.save(ic7);
		ingredientCourseRepos.save(ic8);
		ingredientCourseRepos.save(ic9);
		ingredientCourseRepos.save(ic10);
		ingredientCourseRepos.save(ic11);
		ingredientCourseRepos.save(ic12);
		ingredientCourseRepos.save(ic13);
		ingredientCourseRepos.save(ic14);
		ingredientCourseRepos.save(ic15);
		ingredientCourseRepos.save(ic16);
		ingredientCourseRepos.save(ic17);
		ingredientCourseRepos.save(ic18);
		ingredientCourseRepos.save(ic19);
		ingredientCourseRepos.save(ic20);
		
		
			// insertion d'ami 
		Ami a1= new Ami(null,u2, u3, true);
		Ami a2= new Ami(null,u1, u3, true);
		Ami a3= new Ami(null,u2, u1, true);
		Ami a4=new Ami(null,u1,u4,true);
		Ami a5=new Ami(null,u1,u5,true);
		
		amiRepos.save(a1);
		amiRepos.save(a2);
		amiRepos.save(a3);
		amiRepos.save(a4);
		amiRepos.save(a5);
		
		// insertion d'avis
		
		Avis av1 = new Avis (null, 5, "Très bon", u1,r1);
		Avis av2 = new Avis (null, 2, "Pas terrible", u1,r2);
		Avis av3 = new Avis (null, 4, "Bon", u3,r3);
		Avis av4 = new Avis (null, 1, "Nul", u4,r8);
		avisRepos.save(av1);
		avisRepos.save(av2);
		avisRepos.save(av3);
		avisRepos.save(av4);
		
		// insertion evenement
		Evenement e1 = new Evenement(null, "Repas chez mamie", LocalDate.of(2023, 5, 27), "2 chemin des fleurs 38000 Grenoble", "C'est la fête", u1, null);
		Evenement e2 = new Evenement(null, "Soirée chez jojo", LocalDate.of(2023, 5, 30), "13 avenue des peupliers, 57000 Metz", "Pour fêter mon retour", u2, null);
		Evenement e3 = new Evenement(null, "Anniversaire", LocalDate.of(2023, 6, 27), "2 chemin des fleurs 38000 Grenoble", "Histoire de vous voir", u3, null);
		Evenement e4 = new Evenement(null, "Noel", LocalDate.of(2023, 12, 24), "2 chemin des fleurs 38000 Grenoble", "RDV avec le père Noël", u4,  null);
		Evenement e5 = new Evenement(null, "Soirée jeux", LocalDate.of(2023, 5, 10), "66 rue du bain 69000 Lyon","Ramenez vos meilleurs jeux SVP",  u3,  null);
		Evenement e6 = new Evenement(null, "Raclette", LocalDate.of(2023, 5, 12), "5 impasse des moulins 75000 Paris", "On va manger de ouf",u1, null);
		eventRepos.save(e1);
		eventRepos.save(e2);
		eventRepos.save(e3);
		eventRepos.save(e4);
		eventRepos.save(e5);
		eventRepos.save(e6);
		
		//insertion participe
		Participe p1 = new Participe (null, e1, u1, true);
		Participe p2 = new Participe (null, e1, u2, true);
		Participe p3 = new Participe (null, e1, u3, false);
		Participe p4 = new Participe (null, e2, u1, true);
		Participe p5 = new Participe (null, e2, u4, false);
		participeRepos.save(p1);
		participeRepos.save(p2);
		participeRepos.save(p3);
		participeRepos.save(p4);
		participeRepos.save(p5);
		
		System.out.println("Lancement en cours");
	}

	public static void main(String[] args) {
		SpringApplication.run(FrigidoomApplication.class, args);
		System.out.print("Lancement terminé.");
	}

}
